### ISSUE TITLE
Wine how to?

### ISSUE THREAD

**Issue by Teuwu** [FNA-XNA/FAudio#105]
I read the wiki entry for how to use with Proton, but what needs to be done to use/test FAudio with wine from Winehq?

- What version of wine works?

- Is there any patches that need to be applied to wine to use FAudio?

- where would I put the libFAudio.so so wine will use it?

- should all the xaudio dlls in winecfg be builtin? or any other configuration to wine?

- how would one know that FAudio is being used?

**Comment by flibitijibibo** [comment]
Here's the WineHQ patch, based on 3.21 until 4.0 is out:

https://github.com/flibitijibibo/wine/pull/1

FAudio is built the same, with the addition of `make install` so that Wine's configure script can find the library and headers, and that will take care of finding FAudio at runtime. They can all be builtin or you can just make xaudio2_* builtin, since we can also work with native x3daudio1_* and xapofx1_*.

**Comment by Teuwu** [comment]
For anyone else reading this, the commands to get those 2 patches are:

`wget --output-document=fadio1.patch https://github.com/flibitijibibo/wine/pull/1/commits/1c645a54c557da2afb60f45f13ebb52b859c0be4.patch

wget --output-document=fadio2.patch https://github.com/flibitijibibo/wine/pull/1/commits/5611927ee5a5d755428493a895b4823f9bd1170e.patch`

**Comment by Teuwu** [comment]
so wine 4.0 won't need the patches?

**Comment by Kron4ek** [comment]
@Teuwu you can use MinGW FAudio build with vanilla Wine (and with Staging too), additional patches not needed in this case.

https://github.com/Kron4ek/FAudio-Builds
