### ISSUE TITLE
Read access violation when using ogg file in Medium quality XNB format

### ISSUE THREAD

**Issue by tomcashman** [FNA-XNA/FAudio#285]
XNB files attached. Though I think this might be related to the following issues as I had similar crash on MG before when using Medium quality settings in content pipeline.

 * https://github.com/MonoGame/MonoGame/issues/6701
 * https://github.com/MonoGame/MonoGame/issues/5662

```
FAudio_INTERNAL_Convert_S16_To_F32 Line 192
FAudio_INTERNAL_DecodeMonoMSADPCM Line 1895
```
![image](https://user-images.githubusercontent.com/1745420/167307074-3d06fa50-f7e6-4461-88f5-31704713ef7a.png)

https://drive.google.com/file/d/1eznEknn23nYkBHVvUYZxi-RlpgCygNsI/view?usp=sharing

**Comment by flibitijibibo** [comment]
I'm looking at the files now and they're all just uncompressed PCM, it's not even MSADPCM which makes the stack suspicious... what happens if you just take the masters for those files and replace the XNB files completely? It might actually _save_ disk space because you'll just be reading the wav directly instead of going through the content pipeline encoding which adds stuff to the beginning of the file.

**Comment by flibitijibibo** [comment]
Tested all 5 files on the lab to be sure and they all ran correctly, but these look very much like debug content files since they're totally uncompressed... then again I wouldn't recommend the LZX compression anyway. All 5 sounded like ambient files so this might be the excuse you're looking for to just use the unprocessed ogg files with DynamicSoundEffectInstance.

**Comment by tomcashman** [comment]
I've been investigating further and I can now reproduce this consistently on a simple FNA game using the following SFX files ->

[Content.zip](https://github.com/FNA-XNA/FAudio/files/8647705/Content.zip)

This was the code I was using.

```csharp
	class FNAGame : Game
	{
		private SoundEffect sound;
		private KeyboardState keyboardPrev = new KeyboardState();

		public FNAGame()
		{
			GraphicsDeviceManager gdm = new GraphicsDeviceManager(this);

			// Typically you would load a config here...
			gdm.PreferredBackBufferWidth = 1280;
			gdm.PreferredBackBufferHeight = 720;
			gdm.IsFullScreen = false;
			gdm.SynchronizeWithVerticalRetrace = true;

			// All content loaded will be in a "Content" folder
			Content.RootDirectory = "Content";
		}

		protected override void Initialize()
		{
			/* This is a nice place to start up the engine, after
			 * loading configuration stuff in the constructor
			 */
			base.Initialize();
		}

		protected override void LoadContent()
		{
			// Load textures, sounds, and so on in here...
			base.LoadContent();

			sound = Content.Load<SoundEffect>("sfx_jelly_emote_happy_01.ogg");
		}

		protected override void UnloadContent()
		{
			// Clean up after yourself!
			base.UnloadContent();
		}

		protected override void Update(GameTime gameTime)
		{
			// Run game logic in here. Do NOT render anything here!
			base.Update(gameTime);

			KeyboardState keyboardCur = Keyboard.GetState();

			if (keyboardCur.IsKeyDown(Keys.Space) && keyboardPrev.IsKeyUp(Keys.Space))
			{
				sound.Play();
			}

			keyboardPrev = keyboardCur;
		}

		protected override void Draw(GameTime gameTime)
		{
			// Render stuff in here. Do NOT run game logic in here!
			GraphicsDevice.Clear(Color.CornflowerBlue);
			base.Draw(gameTime);
		}
	}
```

**Comment by flibitijibibo** [comment]
There we go, that file is properly MSADPCM... with a proper weird block alignment:

https://github.com/FNA-XNA/FAudio/commit/155cd2b1e807796a2b66d3c32bc5296022a20ea3

I'm surprised "medium" quality has a block size that big - even XACT didn't go past 512. In any case, fnalibs is updated.

**Comment by tomcashman** [comment]
Thank you for the quick fix 😃
