### ISSUE TITLE
No sound in A Hat in Time on Proton

### ISSUE THREAD

**Issue by fantoro** [FNA-XNA/FAudio#36]
Hey, I built everything and ran the script for DLL overrides but now the audio isn't working at all, there are no error popups etc.

[Steam Log](https://pastebin.com/jVV73TBX)

**Comment by flibitijibibo** [comment]
Going to redirect this to https://github.com/ValveSoftware/Proton/issues/173

The logs won’t show anything so the only way you’ll find out what’s happening is to enable tracing in the COM wrapper. If you’re unsure how to do that you may just want to wait until we integrate this as a builtin.

Also I dunno if you excluded our X3DAudio as recommended so that could be a problem too.

**Comment by flibitijibibo** [comment]
Discovered these while working on something else, maybe it applies here: https://github.com/FNA-XNA/FAudio/commit/8a58e9d7f26d6c572c42c01547cb4ee07404300e
