### ISSUE TITLE
Fallout 4 (Proton/Steamplay 3.16) with built FAudio & FFMPEG support crashes after some specific occurences.

### ISSUE THREAD

**Issue by mikedebian** [FNA-XNA/FAudio#48]
I don't know how to debug this, but I thought I'd make an issue report. Not used to github, so please excuse me for the lack of information.

Using latest steam/steamplay on Arch (Fully updated).
Used commit 879.

Built FAudio with FFMPEG support and installed using install_fake_dlls to proper directories in the fallout directory (pfx).

Sound works, music works, voices works. Everything works. There's a bit of audio clipping while entering terminal, but that's another issue. I'm not a proffessional, but I can't hear the difference using FAudio and XAudio, so good work!

Anyway, when using fast travel or entering a sanctuary (in my case, the Castle) the game will freeze.
It's not reproducible with XAudio. This happens every time, no matter how I try to enter. It seems there's a specific line I cross from one region over to another (In this case, the castle), and the text should show up "Now entering The Castle". On the same spot, the same pixel evel, the game will crash.

Thunder, etc. works with FAudio though, did not with XAudio (sound would dissapear).

Shooting a missile at a group of raiders/mutants/etc will sometimes freeze the game using FAudio (when there's too many sounds on screen it seems. Same as XAudio, except that XAudio would just dissapear. Using FAudio and the game freezes). This happens frequently.

Fast traveling. Whenever I use fast travel, the loading screen comes up (I have just tested it on a few locations...sanctuaries. Might just be sanctuary related) and it completes the loading. Just when it's about to change from loading screen to game screen, the game freezes. This happens every time.

No output in terminal. Just game executable removed.

**Comment by flibitijibibo** [comment]
I don't have this game so I'll need as much debug information as you can get. If you can get a thread dump from a debugger that'll be the best information possible. Attaching via GDB, pausing, and `thr app all bt` should get us what we want.

**Comment by mikedebian** [comment]
I will try to do what you've asked of me. In the meantime, since I can't see a direct message function on github, and I don't have other social media accounts, please check your inbox on reddit.

**Comment by mikedebian** [comment]
I don't know if I did it right.

I started the game, paused it and attached the PID to gdb, used the thr app all bt command and pressed c for no paging. Typed continue and resumed until crash. This was the output I got.

`[New LWP 11712]
[LWP 11369 exited]
[Detaching after fork from child process 11714]
[LWP 11712 exited]
[New LWP 11715]
[Detaching after fork from child process 11716]
[Detaching after fork from child process 11717]
[LWP 11715 exited]
[New LWP 11719]
[LWP 11719 exited]
[New LWP 11720]

Thread 24 "SDLAudioP2" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 11328]
0x00007f01227f2c24 in ?? ()
(gdb) 
`

**Comment by flibitijibibo** [comment]
Dang, was hoping I'd get something in the audio thread at least... it does say the audio thread segfaulted though, so there's a really good chance it's in FAudio specifically. The WMA stuff is known to crash in one or two scenarios based on the input data, I'm not 100% sure what separates the good data from the bad. I've let someone else know about this and I believe they have FO4 to test with.

**Comment by mikedebian** [comment]
Thank you very much for showing patience with that I can't do a better job at this. I hope something will come out of it, because for the first time I was able to listen to thunder for more than 2 seconds before audio crapped out, amongst other things :)

**Comment by niarbeht** [comment]
I don't know my way around FAudio or it's WMA code well (or at all for that matter), but if there's any internal debug statements I can activate or logging to file I might be able to shove in (or things I can put in that'll show up in GDB's output maybe?) to try to narrow down where things are going wrong, I'd be glad to help.  I can get this bug to happen reliably on my save file.

**Comment by flibitijibibo** [comment]
The best I can recommend is using the patch I submitted to Valve’s Wine branch this afternoon, then using Valgrind:

https://wiki.winehq.org/Wine_and_Valgrind

It will be insanely slow but it will reveal quite a bit when something goes wrong.

If you want to trace around, look at FAudio_INTERNAL_MixSource in FAudio_internal.c. FAudio_ffmpeg.c may also be helpful. Pray that memory doesn’t get corrupted though, otherwise you’ll have no choice but to use Valgrind to find out what happened.

**Comment by niarbeht** [comment]
Putting `/usr/bin/valgrind --log-file=/home/niarbeht/fo4valgrind --trace-children=yes --vex-iropt-register-updates=allregs-at-mem-access %command%` into my launch options for Fallout 4 from Steam doesn't seem to cause Fallout 4 to successfully start.  I do get an output file, however, but I'm not sure it's applicable.

**Comment by flibitijibibo** [comment]
https://github.com/ValveSoftware/wine/pull/32

**Comment by flibitijibibo** [comment]
Managed to get my hands on FO4 and I'm trying things out on Windows with the COM wrapper, and I did find one really odd crash so far:

https://github.com/FNA-XNA/FAudio/blob/master/src/FAudio_ffmpeg.c#L288

It makes no sense that it would crash here; the packetIdx is 0 yet it's trying to read from CumulativeBytes[-1] according to VS, so I'm looking to see how I can avoid that from happening. The disassembly doesn't make much sense either, so I'm just expanding this out and rewriting the same logic to see if I can get it to produce something better.

**Comment by flibitijibibo** [comment]
I'm still super early in the game but I've run for about an hour without crashes after this change (before it only took about 10 minutes to die):

https://github.com/FNA-XNA/FAudio/commit/0f3287a08bb6a945551d21ad695b9100de8df799

If it still dies, this function is where you want to printf spam.

**Comment by mikedebian** [comment]
I played for over an hour now. Entering the castle works, all sounds work, explosions, etc. Fast traveling works. 

Seems you might have nailed the most annoying fallout 4 bug for linux users (and some windows users too!)

**Comment by mmatis** [comment]
I wonder if this would work for SkyrimSE. It has the same audio issues. I have it and am willing to test. Is compiling Valve's WINE similar to compiling regular WINE?

**Comment by niarbeht** [comment]
You don't need to compile all of Wine, just FAudio, and then put the resulting binaries into the correct place in:

- Your Wine install directory, if using your own install of Wine
- Steam's Proton install directory, if playing the game directly from Steam.

**Comment by niarbeht** [comment]
I seem to have occasional hard freeze issues, but I'm definitely able to play the game for much, much longer periods of time.  I have no idea if the hard freezes are related to FAudio or something else, since using the XACT workaround with Winetricks caused so many issues of it's own.

The most recent freeze I ran into was at the Boston public library, during the events that take place there after you find the Nifty Room With The Stuff In It (avoiding very minor worldbuilding spoilers in case anyone cares).

**Comment by mmatis** [comment]
I've got it, compiled it, and plopped it into the lib64 folder of my WINE install. Anything I need to set in winecfg? do I just set xaudio2_7 to builtin?

**Comment by flibitijibibo** [comment]
Just got back this evening after letting an instance with music idle for about 3.5 hours, so far everything is okay... so at least crashes aren't happening I guess.

If the game freezes, try to attach to the process and get a thread dump (see posts toward the top), if FAudio is the culprit one of the threads should be fully readable and contain FAudio symbols inside.

For now, if you're not prepared to debug a Wine application (which is admittedly a little harder than a plain Linux application), this probably isn't ready for you yet, since things going wrong with an audio subsystem can get _really_ nasty (we're talking full-volume YTP levels of nasty audio). Expect updates for an official release after Andrew and I have cleaned everything up and run through our current test suite. The patch should be submitted in November but I have no idea when it will get accepted.

**Comment by mmatis** [comment]
Started a new game on a clean install of SkyrimSE and WINE 3.16 with Faudio. Got all the way through the Helgen sequence and through the tutorial with no sound issues!! That's huge because sound always dies either on the cart, when the dragon shows up, or before entering the keep.... But then I got a hard freeze on the road to Riverwood. Twice. Almost in the same spot-- As you approach the river and more ambient sounds kick in. I'll do the valgrind thing this weekend when I have more time, but so far this is VERY promising! Not sure if it's relevant, but this was in the terminal output after I killed the game:

`[wmav2 @ 0x7fd184124f80] nb_frames is 0 bits left 11888
[wmav2 @ 0x7fd1841b6800] nb_frames is 0 bits left 11888
0110:fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x4090409, 0000: semi-stub!
[wmav2 @ 0x7fd18417a7c0] nb_frames is 0 bits left 11888
[wmav2 @ 0x7fd1840b5380] nb_frames is 0 bits left 11888
[wmav2 @ 0x7fd18413d2c0] nb_frames is 0 bits left 11888
[wmav2 @ 0x7fd18411d180] nb_frames is 0 bits left 11888
[wmav2 @ 0x7fd1842c19c0] nb_frames is 0 bits left 11888
[wmav2 @ 0x7fd1842723c0] nb_frames is 0 bits left 11888
[wmav2 @ 0x7fd1840be0c0] nb_frames is 0 bits left 11888
[wmav2 @ 0x7fd1841409c0] nb_frames is 0 bits left 11888
[wmav2 @ 0x7fd1840647c0] nb_frames is 0 bits left 11888
[wmav2 @ 0x7fd1840be0c0] nb_frames is 0 bits left 11888
`

**Comment by Rabcor** [comment]
> wmav2
Those are WMA2 files being played, so it seems possible that it's related to faudio. It may even be the same issue that niarbeht mentioned earlier. I'm keeping an eye on this because I managed to get a heavily modded skyrimSE working in lutris but it was unplayable due to sound issues that occurred due to mods/configuration,.

I'd join in on the testing, but I don't quite understand how to patch Proton's Wine, unless I'm just overcomplicating it and I should just be compiling the entirety of proton from git rather than just the wine component; but even then, I'm not sure how to actually use proton compiled from source either.

I'm pretty excited about the idea of finally being able to play the game properly on linux, even with the occasional CTD, that's just the classic bethesda experience anyways haha.

**Comment by flibitijibibo** [comment]
If you’re not experienced with Wine builds and Wine debugging then the best solution is to just wait.

**Comment by Rabcor** [comment]
> If you’re not experienced with Wine builds and Wine debugging then the best solution is to just wait.

Well I'm not experienced with either, but it's never too late to start learning is it?

**Comment by mikedebian** [comment]
Well, played for 6 hours, no errors, just two random crashes that were not sound related. Mark as fixed? (This specific bug about FO4)

**Comment by mikedebian** [comment]
It's weird. I can get sound in intro video now, but all sound in game is lost. I'm able to talk to NPC's though, so it's just not registering out of the speakers. Must have been an upgrade on my side. Can you confirm? Using latest revision.

**Comment by flibitijibibo** [comment]
Cannot confirm. Would need a bisect if something new caused a problem.

**Comment by mikedebian** [comment]
I verified the game files as skyrim worked. All files verified successfully, but I deleted and redownloaded the game either way and now it works. No 3rd party files in the folder used. Weird, at least not related to faudio. Sorry to bother.
